force-app/main/default/objects/SCIF_Request__c/SCIF_Request__c.object-meta.xml
<CustomObject>
    <label>SCIF Request</label>
    <nameField>
        <label>SCIF Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCIF Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCIF_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>EASP Review</fullName>
            </value>
            <value>
                <fullName>PBRO Review</fullName>
            </value>
            <value>
                <fullName>CFO Review</fullName>
            </value>
            <value>
                <fullName>CBRO Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCIF_Request__c/recordTypes/Terminate_A_Relationship.recordType-meta.xml
<RecordType>
    <fullName>Terminate_A_Relationship</fullName>
    <active>true</active>
    <label>Terminate A Relationship</label>
</RecordType>

force-app/main/default/classes/GuidanceTextController_Test.cls
@isTest class GuidanceTextController_Test {
    
    static Id recordTypeId {get; set;}
    
    static {
        String RecordTypeDeveloperName = 'Terminate_A_Relationship';
        recordTypeId = Schema.SObjectType.SCIF_Request__c.getRecordTypeInfosByDeveloperName().get(RecordTypeDeveloperName).getRecordTypeId();
    }
    
    static testMethod void firstData(){
        SCIF_Request__c request = new SCIF_Request__c();
        request.RecordTypeId = recordTypeId;
        request.Name = '';
        request.Status__c = 'PBRO Review';
        insert request;
        
        GuidanceTextController.getScifRecord(request.Id);
    } 

}