force-app/main/default/objects/GuidanceText__mdt/GuidanceText__mdt.object-meta.xml
<CustomObject>
    <label>Sample MD</label>
    <pluralLabel>Sample MD</pluralLabel>
</CustomObject>

force-app/main/default/objects/GuidanceText__mdt/fields/GuidanceText__c.field-meta.xml
<CustomField>
    <fullName>GuidanceText__c</fullName>
    <label>GuidanceText</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GuidanceText__mdt/fields/RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeName__c</fullName>
    <label>RecordTypeName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCIF_Request__c/SCIF_Request__c.object-meta.xml
<CustomObject>
    <label>SCIF Request</label>
    <nameField>
        <label>SCIF Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCIF Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCIF_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>EASP Review</fullName>
            </value>
            <value>
                <fullName>PBRO Review</fullName>
            </value>
            <value>
                <fullName>CFO Review</fullName>
            </value>
            <value>
                <fullName>CBRO Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GuidanceTextController.cls
public class GuidanceTextController {
    
    public static Map<String,String> recTypeStatusWiseMessage {get; private set;}
    
    static{
        recTypeStatusWiseMessage = new Map<String,String>();
        //loading all values from custom metadata
        List<GuidanceText__mdt> textList = [Select id,
                                            GuidanceText__c, 
                                            RecordTypeName__c,
                                            Status__c 
                                            from GuidanceText__mdt];
        for(GuidanceText__mdt gtext:textList){
            //key = recordTypeName+'_'+status
            //value = Guidance Text
            String key = gtext.RecordTypeName__c + '_'+gtext.Status__c.replace(' ','_');
            String val = gtext.GuidanceText__c;
            recTypeStatusWiseMessage.put(key,val);
        }
    }
    
    @AuraEnabled public static String getScifRecord(String recordId){
        String recordTypeName;
        String status;
        String key;
        List<SCIF_Request__c> SCIFList = [SELECT Id, RecordType.DeveloperName , Status__c FROM SCIF_Request__c where Id=:recordId];
        recordTypeName = SCIFList[0].RecordType.DeveloperName ;
        status = SCIFList[0].Status__c.replace(' ','_'); 
        key = recordTypeName+'_'+status ;
        return recTypeStatusWiseMessage.containsKey(key)?recTypeStatusWiseMessage.get(key):'';
        
        
    }
    @AuraEnabled
    public static Account getAcc(String s){
        Account acc =[Select id , name from account where name =:s limit 1];
        return acc;
    }
}